/** CREATE A SCHEMA FOR LOCAL TESTING ***/

//DROP IF EXISTS
DROP SCHEMA IF EXISTS ATHENA;

// CREATE SCHEMA
CREATE SCHEMA ATHENA AUTHORIZATION SA;

// CREATE THE DATA_SOURCE TABLE
CREATE TABLE SOURCE
(
  ID          INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
  NAME        VARCHAR(50)                        NOT NULL,
  URL         VARCHAR(255)                       NOT NULL,
  SOURCE_TYPE VARCHAR(255)                       NOT NULL,
  DESCRIPTION CLOB
);

CREATE UNIQUE INDEX "SOURCE_NAME_uindex" ON SOURCE (NAME)